# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  LT_USERNAME: "kaustubhd"
  LT_ACCESS_KEY: ""

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g lambdatest-cypress-cli
    lambdatest-cypress init
    lambdatest-cypress run
  displayName: 'npm install and build'
